services:
  - type: web
    name: cedric_houseplan_backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn cedric_admin.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: USE_SQLITE
        value: "False"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.yulpvfabkynqspiroghb
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: aws-1-eu-west-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_SSLMODE
        value: require
      - key: ALLOWED_HOSTS
        value: "cedric-houseplan-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://cedric-houseplan2.vercel.app"
